name: CI - Run Jest Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # ----------------- BACKEND -----------------
      - name: Install backend dependencies
        working-directory: ./backend
        run: npm install

      - name: Run backend tests with coverage
        working-directory: ./backend
        run: npm run test:coverage

      - name: Upload backend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: backend-coverage
          path: backend/coverage/

      # ----------------- FRONTEND -----------------
      - name: Install frontend dependencies
        working-directory: ./app
        run: npm install

      - name: Run frontend tests with coverage
        working-directory: ./app
        run: npm test -- --coverage --watchAll=false

      - name: Upload frontend coverage report
        uses: actions/upload-artifact@v4
        with:
          name: frontend-coverage
          path: app/coverage/
